package com.as.publichealth.domain.tjwz;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.ToString;

import java.util.Date;

/**
 * HEALTH_TJWZ
 * 
 * @author wgy
 * @version 1.0.0 2020-04-08
 */
@Data
@ToString
@TableName("health_tjwz")
public class HealthTjwz {
    /** 版本号 */
    private static final long serialVersionUID = -8688927818983755968L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** 体检编号 */
    private String tjbh;

    /** 条码号 */
    private String tmh;

    /** 体检日期 */
    private Date tjrq;

    /** 责任医生 */
    private String zrys;

    /** 症状 */
    private String zz;

    /** 其他症状 */
    private String zzqt;

    /** 体温 */
    private Float tw;

    /** 脉率 */
    private Integer ml;

    /** 呼吸频率 */
    private Integer hxpl;

    /** 腰围 */
    private Integer yw;

    /** 健康状态评估 */
    private Integer jkztpg;

    /** 自理能力评估 */
    private Integer zlnlpg;

    /** 认知功能 */
    private Integer rzgn;

    /** 情感状态 */
    private Integer qgzt;

    /** 锻炼频率 */
    private String dlpl;

    /** 每次锻炼时间 */
    private String mcdlsj;

    /** 坚持锻炼时间 */
    private String jcdlsj;

    /** 锻炼方式 */
    private String dlfs;

    /** 饮食习惯 */
    private String ysxg;

    /** 吸烟状况 */
    private String xyzk;

    /** 日吸烟量 */
    private String rxyl;

    /** 开始吸烟年龄 */
    private Integer ksxynl;

    /** 戒烟年龄 */
    private Integer jynl;

    /** 饮酒频率 */
    private String yjpl;

    /** 日饮酒 量 */
    private String ryjl;

    /** 是否戒酒 */
    private String sfjj;

    /** 戒酒年龄 */
    private Integer jjnl;

    /** 开始饮酒年龄 */
    private Integer ksyjnl;

    /** 是否醉酒 */
    private String sfzj;

    /** 饮酒种类 */
    private String yjzl;

    /** 饮酒种类其他 */
    private String yjzlqt;

    /** 职业病接触史 */
    private String zybjcs;

    /** 口唇 */
    private String kc;

    /** 齿列 */
    private String cl;

    /** 左上缺齿 */
    private String qczs;

    /** 左下缺齿 */
    private String qczx;

    /** 右上缺齿 */
    private String qcys;

    /** 右下缺齿 */
    private String qcyx;

    /** 左上龋齿 */
    private String quczs;

    /** 左下龋齿 */
    private String quczx;

    /** 右上龋齿 */
    private String qucys;

    /** 右下龋齿 */
    private String qucyx;

    /** 左上义齿 */
    private String yczs;

    /** 左下义齿 */
    private String yczx;

    /** 右上义齿 */
    private String ycys;

    /** 右下义齿 */
    private String ycyx;

    /** 咽部 */
    private String yb;

    /** 左眼视力 */
    private Float zysl;

    /** 右眼视力 */
    private Float yysl;

    /** 左眼矫正视力 */
    private String zyjzsl;

    /** 右眼矫正视力 */
    private String yyjzsl;

    /** 听力 */
    private String tl;

    /** 运动功能 */
    private String ydgn;

    /** 眼底 */
    private String yd;

    /** 眼底异常 */
    private String ydyc;

    /** 皮肤 */
    private String pf;

    /** 皮肤其他 */
    private String pfqt;

    /** 巩膜 */
    private String gm;

    /** 巩膜其他 */
    private String gmqt;

    /** 淋巴结 */
    private String lbj;

    /** 淋巴结其他 */
    private String lbjqt;

    /** 桶状胸 */
    private String tzx;

    /** 呼吸音 */
    private String hxy;

    /** 呼吸音异常 */
    private String hxyyc;

    /** 罗音 */
    private String ly;

    /** 罗音其他 */
    private String lyqt;

    /** 心律 */
    private String xinlv;

    /** 杂音 */
    private String zy;

    /** 杂音其他 */
    private String zyqt;

    /** 压痛 */
    private String yt;

    /** 压痛其他 */
    private String ytqt;

    /** 包块 */
    private String bk;

    /** 包块其他 */
    private String bkqt;

    /** 肝大 */
    private String gd;

    /** 肝大其他 */
    private String gdqt;

    /** 脾大 */
    private String pd;

    /** 脾大其他 */
    private String pdqt;

    /** 移动性浊音 */
    private String ydxzy;

    /** 移动性浊音其他 */
    private String ydxzyqt;

    /** 下肢水肿 */
    private String xzsz;

    /** 足背动脉搏动 */
    private String zbdmbd;

    /** 脑血管疾病 */
    private String nxgjb;

    /** 脑血管疾病其他 */
    private String nxgjbqt;

    /** 肾脏疾病 */
    private String szjb;

    /** 肾脏疾病其他 */
    private String szjbqt;

    /** 心脏疾病 */
    private String xzjb;

    /** 心脏疾病其他 */
    private String xzjbqt;

    /** 血管疾病 */
    private String xgjb;

    /** 血管疾病其他 */
    private String xgjbqt;

    /** 眼部疾病 */
    private String ybjb;

    /** 眼部疾病其他 */
    private String ybjbqt;

    /** 神经系统疾病 */
    private String sjxtjb;

    /** 神经系统疾病其他 */
    private String sjxtjbqt;

    /** qtxtjb */
    private String qtxtjb;

    /** qtxtjbqt */
    private String qtxtjbqt;

    /** 健康评价 */
    private String jkpj;

    /** 健康评价异常1 */
    private String jkpjyc1;

    /** 健康评价异常2 */
    private String jkpjyc2;

    /** 健康评价异常3 */
    private String jkpjyc3;

    /** 健康评价异常4 */
    private String jkpjyc4;

    /** 健康指导 */
    private String jkzd;

    /** 危险因素控制 */
    private String wxyskz;

    /** 危险因素控制体重 */
    private String wxyskztz;

    /** 危险因素控制疫苗 */
    private String wxyskzym;

    /** 危险因素控制其他 */
    private String wxyskzqt;

    /** 体检年份 */
    private Date tjnf;

    /** 机构编号 */
    private String orgno;

    /** 机构名称 */
    private String orgname;

    /** 创建时间 */
    private Date createtime;

    /** 更新时间 */
    private Date updatetime;


}