package com.as.android.domain.autoupdate;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.ToString;

import java.util.Date;

/**
 * AUTOUPDATE
 * 
 * @author wgy
 * @version 1.0.0 2020-04-15
 */
@Data
@ToString
@TableName("autoupdate")
public class Autoupdate {
    /** 版本号 */
    private static final long serialVersionUID = 6856471190117759818L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 主键 */
    @ApiModelProperty("id")
    @TableId(value = "id", type = IdType.AUTO)
    private Integer id;

    /** appID */
    @ApiModelProperty("appID")
    @TableField(value = "appID")
    private Integer appID;

    /** app名字 */
    @ApiModelProperty("app名字")
    @TableField(value = "appname")
    private String appname;

    /** appcode */
    @ApiModelProperty("appcode")
    @TableField(value = "appcode")
    private String appcode;

    /** 服务器版本号 */
    @ApiModelProperty("服务器版本号")
    @TableField(value = "serverVersion")
    private String serverVersion;

    /** 是否强制更新(1:是,2:不是) */
    @ApiModelProperty("是否强制更新(1:是,2:不是)")
    @TableField(value = "lastForce")
    private String lastForce;

    /** apk下载地址 */
    @ApiModelProperty("apk下载地址")
    @TableField(value = "updateurl")
    private String updateurl;

    /** 版本的更新的描述 */
    @ApiModelProperty("版本的更新的描述")
    @TableField(value = "upgradeinfo")
    private String upgradeinfo;

    /** 上传时间 */
    @ApiModelProperty("上传时间")
    @TableField(value = "uploadtime")
    private Date uploadtime;
}