package com.as.publichealth.domain.main;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.ToString;

import java.util.Date;

/**
 * HEALTH_MAIN
 * 
 * @author wgy
 * @version 1.0.0 2020-04-08
 */
@Data
@ToString
@TableName("health_main")
public class HealthMain {
    /** 版本号 */
    private static final long serialVersionUID = 761198498372989796L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 主键 */
    private Integer id;

    /** 体检编号 */
    private String tjbh;

    /** 档案编号 */
    private String personalid;

    /** 身份证 */
    private String sfz;

    /** 姓名 */
    private String xm;

    /** tmh */
    private String tmh;

    /** 性别 */
    private String sex;

    /** 出生日期 */
    private Date csrq;

    /** 年龄 */
    private Integer age;

    /** 民族 */
    private String mz;

    /** 血型 */
    private String xx;

    /** 联系电话 */
    private String lxdh;

    /** 地址 */
    private String address;

    /** 体检日期 */
    private Date tjrq;

    /** 问诊状态 */
    private Integer wzzt;

    /** 检验状态 */
    private Integer jyzt;

    /** 心电图状态,1：已审核 */
    private Integer xdtzt;

    /** 健康评价 */
    private Integer jkpj;

    /** 自理能力 */
    private Integer zlnl;

    /** 中医体质 */
    private Integer zytz;

    /** 审核状态 */
    private Integer sjzt;

    /** 上传状态 */
    private Integer sczt;

    /** 体检报告打印时间 */
    private Date tjdysj;

    /** 存档报告打印时间 */
    private Date cddysj;

    /** 签名状态 */
    private String qmzt;

    /** 车牌号 */
    private String carno;

    /** 车辆负责人 */
    private String carfzr;

    /** 状态 */
    private String state;

    /** 体检类型 */
    private String type;

    /** 数据来源 */
    private String datasource;

    /** tjnf */
    private Date tjnf;

    /** 机构编号 */
    private Integer orgno;

    /** 机构名称 */
    private String orgname;

    /** tjbgpwd */
    private String tjbgpwd;

    /** 创建时间 */
    private String createtime;

    /** 更新时间 */
    private String updatetime;

}