package com.as.upload.domain.gxysf;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.KeySequence;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.ToString;


import java.util.Date;

/**
 * 高血压患者随访数据表(HD_GXYSF)
 * 
 * @author wgy
 * @version 1.0.0 2020-02-29
 */


@Data
@ToString
@TableName("HD_GXYSF")
@KeySequence(value="S_HD_GXYSF",clazz=Long.class)
public class HdGxysf {
    /** 版本号 */
    private static final long serialVersionUID = 2388762733784068461L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 随访编号 */
    private String sfbh;

    @ApiModelProperty("主键")
    @TableId(type=IdType.INPUT)  //注意主键类型要指定为Input
    private Long id;

    /** 城乡居民健康档案编号 */
    private String personalid;

    /** 身份证 */
    private String sfz;

    /** 建表时间 */
    private String sfrq;

    /** 随访方式代码1门诊 2家庭 3电话 */
    private String sffs;

    /** 症状代码组合1无症状   2头痛头晕   3恶心呕吐      4眼花耳鸣     5呼吸困难    6心悸胸闷   7鼻衄出血不止      8四肢发麻    9下肢水肿 */
    private String zz;

    /** 其他症状描述 */
    private String zzqt;

    /** 收缩压(mmHg) */
    private String ssy;

    /** 舒张压(mmHg) */
    private String szy;

    /** 身高(cm) */
    private String sg;

    /** 体重(kg) */
    private String tz;

    /** 目标体重（kg) */
    private String mbtz;

    /** 体质指数 */
    private String tzzs;

    /** 目标体质指数 */
    private String mbtzzs;

    /** 心率(次/min) */
    private String xl;

    /** 其他体征指数 */
    private String qttz;

    /** 日吸烟量（支） */
    private String rxyl;

    /** 目标日吸烟量（支） */
    private String mbrxyl;

    /** 日饮酒量（两） */
    private String ryjl;

    /** 目标日饮酒量(两） */
    private String mbryjl;

    /** 运动频率(分钟/次) */
    private String ydcs;

    /** 目标运动频率(分钟/次) */
    private String mbydcs;

    /** 每次锻炼时间(min)分钟/次 */
    private String ydsj;

    /** 目标每次锻炼时间(min)分钟/次 */
    private String mbydsj;

    /** 摄盐量分级代码(轻/中/重) */
    private String syqk;

    /** 目标摄盐量分级代码 */
    private String mbsyqk;

    /** 心理调整(1良好  2一般  3差) */
    private String xltz;

    /** 遵医行为评价代码(1良好  2一般  3差) */
    private String zyxw;

    /** 辅助检查 */
    private String fzjc;

    /** 服药依从性代码1规律2间断3不服药 */
    private String fyycx;

    /** 药物不良反应标志1无 2有 */
    private String ywblfy;

    /** 药物不良反应描述 */
    private String ywblfyms;

    /** 随访评价结果代码1控制满意    2控制不满意    3不良反应       4并发症 */
    private String ccsffl;

    /** 下一步管理措施1常规随访   2第1次控制不满意2周随访  3两次控制不满意转诊随访
4紧急转诊
 */
    private String glcs;

    /** 转诊原因 */
    private String zzyy;

    /** 转诊机构科别 */
    private String jgkb;

    /** 本次转诊联系人及电话 */
    private String lxrdh;

    /** 转诊结果代码1到位   2不到位 */
    private String zzjg;

    /** 随访医生建议 */
    private String sfjy;

    /** 下次随访日期 */
    private String xcsfrq;

    /** 责任医师姓名 */
    private String sfys;

    /** 随访医师URL */
    private String sfysUrl;

    /** 居民姓名 */
    private String jm;

    /** 居民URL */
    private String jmUrl;

    /** 创建机构 */
    private String createorg;

    /** 更新机构 */
    private String updateorg;

    /** 创建时间 */
    private Date createtime;

    /** 更新时间 */
    private Date updatetime;

    /** 创建人 */
    private String createrUserId;

    /** 修改人 */
    private String modifiedUserId;

    /** 删除标识 */
    private String delflag;

    /** 失访原因 */
    private String sfyy;

    /** 死亡日期 */
    private String swrq;

    /** 死亡原因 */
    private String swyy;

    /** RES0 */
    private String res0;

    /** RES1 */
    private String res1;

    /** RES2 */
    private String res2;

    /** RES3 */
    private String res3;

    /** RES4 */
    private String res4;

    /** RES5 */
    private String res5;

    /** RES6 */
    private String res6;

    /** RES7 */
    private String res7;

    /** RES8 */
    private String res8;

    /** RES9 */
    private String res9;

    /** 生活方式改变监测代码。1限盐 2减少吸烟量或戒烟 3减少饮酒量或戒酒 4合理膳食 5减轻体重 6适量运动 7放松精神 8心理调整 9其他 */
    private String shfsgbjc;

    /** 生活方式改变监测代码其他 */
    private String shfsgbjcqt;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

}